import "./musicDataInit"
import './frequencySpectrumDisplay'
import "./style.css"
import "./musicDataGet"
import '../assets/images/next.png'
import '../assets/images/play.png'
import '../assets/images/previous.png'
import '../assets/images/random_play.png'
import '../assets/images/sequence_play.png'
import '../assets/images/simple_cycle_play.png'
import '../assets/images/stop.png'
import '../assets/images/volume.png'
import '../assets/images/music_list.png'
import './audioControls'
import './progressBar'
