import "./style.css"
import "./musicCache"
import './audioControl'
import '../assets/images/next.png'
import '../assets/images/play.png'
import '../assets/images/previous.png'
import '../assets/images/random_play.png'
import '../assets/images/sequence_play.png'
import '../assets/images/simple_cycle_play.png'
import '../assets/images/stop.png'
import '../assets/music/1.mp3'
